// Code generated by protoc-gen-go.
// source: net.proto
// DO NOT EDIT!

/*
Package chord is a generated protocol buffer package.

It is generated from these files:
	net.proto

It has these top-level messages:
	Vnode
	VnodeError
	VnodeListErr
	BoolErr
	FindSuccReq
	StringParam
	VnodePair
	ErrResponse
*/
package chord

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vnode struct {
	Id   []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
}

func (m *Vnode) Reset() { *m = Vnode{} }

func (m *Vnode) String() string            { return proto.CompactTextString(m) }
func (*Vnode) ProtoMessage()               {}
func (*Vnode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VnodeError struct {
	VN  *Vnode `protobuf:"bytes,1,opt,name=VN" json:"VN,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *VnodeError) Reset()                    { *m = VnodeError{} }
func (m *VnodeError) String() string            { return proto.CompactTextString(m) }
func (*VnodeError) ProtoMessage()               {}
func (*VnodeError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VnodeError) GetVN() *Vnode {
	if m != nil {
		return m.VN
	}
	return nil
}

type VnodeListErr struct {
	Err    string   `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Vnodes []*Vnode `protobuf:"bytes,2,rep,name=vnodes" json:"vnodes,omitempty"`
}

func (m *VnodeListErr) Reset()                    { *m = VnodeListErr{} }
func (m *VnodeListErr) String() string            { return proto.CompactTextString(m) }
func (*VnodeListErr) ProtoMessage()               {}
func (*VnodeListErr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VnodeListErr) GetVnodes() []*Vnode {
	if m != nil {
		return m.Vnodes
	}
	return nil
}

type BoolErr struct {
	Ok  bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *BoolErr) Reset()                    { *m = BoolErr{} }
func (m *BoolErr) String() string            { return proto.CompactTextString(m) }
func (*BoolErr) ProtoMessage()               {}
func (*BoolErr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type FindSuccReq struct {
	VN    *Vnode `protobuf:"bytes,1,opt,name=VN" json:"VN,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Key   []byte `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *FindSuccReq) Reset()                    { *m = FindSuccReq{} }
func (m *FindSuccReq) String() string            { return proto.CompactTextString(m) }
func (*FindSuccReq) ProtoMessage()               {}
func (*FindSuccReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FindSuccReq) GetVN() *Vnode {
	if m != nil {
		return m.VN
	}
	return nil
}

type StringParam struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *StringParam) Reset()                    { *m = StringParam{} }
func (m *StringParam) String() string            { return proto.CompactTextString(m) }
func (*StringParam) ProtoMessage()               {}
func (*StringParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type VnodePair struct {
	Target *Vnode `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Self   *Vnode `protobuf:"bytes,2,opt,name=self" json:"self,omitempty"`
}

func (m *VnodePair) Reset()                    { *m = VnodePair{} }
func (m *VnodePair) String() string            { return proto.CompactTextString(m) }
func (*VnodePair) ProtoMessage()               {}
func (*VnodePair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *VnodePair) GetTarget() *Vnode {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *VnodePair) GetSelf() *Vnode {
	if m != nil {
		return m.Self
	}
	return nil
}

type ErrResponse struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *ErrResponse) Reset()                    { *m = ErrResponse{} }
func (m *ErrResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrResponse) ProtoMessage()               {}
func (*ErrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*Vnode)(nil), "chord.Vnode")
	proto.RegisterType((*VnodeError)(nil), "chord.VnodeError")
	proto.RegisterType((*VnodeListErr)(nil), "chord.VnodeListErr")
	proto.RegisterType((*BoolErr)(nil), "chord.BoolErr")
	proto.RegisterType((*FindSuccReq)(nil), "chord.FindSuccReq")
	proto.RegisterType((*StringParam)(nil), "chord.StringParam")
	proto.RegisterType((*VnodePair)(nil), "chord.VnodePair")
	proto.RegisterType((*ErrResponse)(nil), "chord.ErrResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Chord service

type ChordClient interface {
	ListVnodesServe(ctx context.Context, in *StringParam, opts ...grpc.CallOption) (*VnodeListErr, error)
	PingServe(ctx context.Context, in *Vnode, opts ...grpc.CallOption) (*BoolErr, error)
	NotifyServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*VnodeListErr, error)
	GetPredecessorServe(ctx context.Context, in *Vnode, opts ...grpc.CallOption) (*VnodeError, error)
	FindSuccessorsServe(ctx context.Context, in *FindSuccReq, opts ...grpc.CallOption) (*VnodeListErr, error)
	ClearPredecessorServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*ErrResponse, error)
	SkipSuccessorServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*ErrResponse, error)
}

type chordClient struct {
	cc *grpc.ClientConn
}

func NewChordClient(cc *grpc.ClientConn) ChordClient {
	return &chordClient{cc}
}

func (c *chordClient) ListVnodesServe(ctx context.Context, in *StringParam, opts ...grpc.CallOption) (*VnodeListErr, error) {
	out := new(VnodeListErr)
	err := grpc.Invoke(ctx, "/chord.chord/ListVnodesServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) PingServe(ctx context.Context, in *Vnode, opts ...grpc.CallOption) (*BoolErr, error) {
	out := new(BoolErr)
	err := grpc.Invoke(ctx, "/chord.chord/PingServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) NotifyServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*VnodeListErr, error) {
	out := new(VnodeListErr)
	err := grpc.Invoke(ctx, "/chord.chord/NotifyServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) GetPredecessorServe(ctx context.Context, in *Vnode, opts ...grpc.CallOption) (*VnodeError, error) {
	out := new(VnodeError)
	err := grpc.Invoke(ctx, "/chord.chord/GetPredecessorServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) FindSuccessorsServe(ctx context.Context, in *FindSuccReq, opts ...grpc.CallOption) (*VnodeListErr, error) {
	out := new(VnodeListErr)
	err := grpc.Invoke(ctx, "/chord.chord/FindSuccessorsServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) ClearPredecessorServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*ErrResponse, error) {
	out := new(ErrResponse)
	err := grpc.Invoke(ctx, "/chord.chord/ClearPredecessorServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) SkipSuccessorServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*ErrResponse, error) {
	out := new(ErrResponse)
	err := grpc.Invoke(ctx, "/chord.chord/SkipSuccessorServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Chord service

type ChordServer interface {
	ListVnodesServe(context.Context, *StringParam) (*VnodeListErr, error)
	PingServe(context.Context, *Vnode) (*BoolErr, error)
	NotifyServe(context.Context, *VnodePair) (*VnodeListErr, error)
	GetPredecessorServe(context.Context, *Vnode) (*VnodeError, error)
	FindSuccessorsServe(context.Context, *FindSuccReq) (*VnodeListErr, error)
	ClearPredecessorServe(context.Context, *VnodePair) (*ErrResponse, error)
	SkipSuccessorServe(context.Context, *VnodePair) (*ErrResponse, error)
}

func RegisterChordServer(s *grpc.Server, srv ChordServer) {
	s.RegisterService(&_Chord_serviceDesc, srv)
}

func _Chord_ListVnodesServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).ListVnodesServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/ListVnodesServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).ListVnodesServe(ctx, req.(*StringParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_PingServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vnode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).PingServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/PingServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).PingServe(ctx, req.(*Vnode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_NotifyServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VnodePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).NotifyServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/NotifyServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).NotifyServe(ctx, req.(*VnodePair))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_GetPredecessorServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vnode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetPredecessorServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/GetPredecessorServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetPredecessorServe(ctx, req.(*Vnode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_FindSuccessorsServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSuccReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).FindSuccessorsServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/FindSuccessorsServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).FindSuccessorsServe(ctx, req.(*FindSuccReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_ClearPredecessorServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VnodePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).ClearPredecessorServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/ClearPredecessorServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).ClearPredecessorServe(ctx, req.(*VnodePair))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_SkipSuccessorServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VnodePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).SkipSuccessorServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/SkipSuccessorServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).SkipSuccessorServe(ctx, req.(*VnodePair))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chord_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chord.chord",
	HandlerType: (*ChordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListVnodesServe",
			Handler:    _Chord_ListVnodesServe_Handler,
		},
		{
			MethodName: "PingServe",
			Handler:    _Chord_PingServe_Handler,
		},
		{
			MethodName: "NotifyServe",
			Handler:    _Chord_NotifyServe_Handler,
		},
		{
			MethodName: "GetPredecessorServe",
			Handler:    _Chord_GetPredecessorServe_Handler,
		},
		{
			MethodName: "FindSuccessorsServe",
			Handler:    _Chord_FindSuccessorsServe_Handler,
		},
		{
			MethodName: "ClearPredecessorServe",
			Handler:    _Chord_ClearPredecessorServe_Handler,
		},
		{
			MethodName: "SkipSuccessorServe",
			Handler:    _Chord_SkipSuccessorServe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "net.proto",
}

func init() { proto.RegisterFile("net.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0xdf, 0xeb, 0xd2, 0x50,
	0x14, 0x4f, 0xf7, 0x9d, 0xb5, 0x33, 0x31, 0xbb, 0x16, 0x88, 0x04, 0xc9, 0xea, 0x21, 0x10, 0x7c,
	0x30, 0x88, 0x1e, 0x84, 0xa2, 0xc8, 0x5e, 0x42, 0xc6, 0x06, 0xbe, 0xaf, 0xed, 0xa8, 0xc3, 0xb5,
	0x6b, 0xf7, 0x5e, 0x05, 0xff, 0xa0, 0xfe, 0xcf, 0xee, 0x3d, 0xbb, 0xca, 0x72, 0x4a, 0xf4, 0x76,
	0xce, 0x3d, 0x9f, 0x1f, 0xe7, 0xc7, 0x06, 0x5e, 0x89, 0x6a, 0xba, 0x17, 0x5c, 0x71, 0xe6, 0xa6,
	0x5b, 0x2e, 0xb2, 0x60, 0x02, 0xee, 0xaa, 0xe4, 0x19, 0xb2, 0x1e, 0xb4, 0xf3, 0x6c, 0xd8, 0x1a,
	0xb7, 0xde, 0x76, 0x23, 0x1d, 0x31, 0x06, 0x0f, 0x5b, 0x2e, 0xd5, 0xb0, 0xad, 0x5f, 0xbc, 0x88,
	0xe2, 0x60, 0x0e, 0x40, 0xe0, 0xaf, 0x42, 0x70, 0xc1, 0x5e, 0x42, 0x7b, 0xb5, 0x24, 0x86, 0x3f,
	0xeb, 0x4e, 0x49, 0x6e, 0x4a, 0xe5, 0x48, 0xbf, 0xb3, 0x3e, 0x38, 0x28, 0x84, 0xa5, 0x9b, 0x30,
	0x58, 0x40, 0x97, 0xca, 0xdf, 0x73, 0xa9, 0xb4, 0xc2, 0x19, 0xd1, 0xba, 0x20, 0xd8, 0x1b, 0xe8,
	0x1c, 0x0d, 0x42, 0x6a, 0x9a, 0xd3, 0x50, 0xb5, 0x35, 0xdd, 0xf2, 0xe3, 0xcf, 0x9c, 0x17, 0x46,
	0x42, 0x37, 0xcd, 0x77, 0xa4, 0xf0, 0x24, 0xd2, 0xd1, 0x0d, 0xd3, 0x18, 0xfc, 0x45, 0x5e, 0x66,
	0xf1, 0x21, 0x4d, 0x23, 0xfc, 0xf5, 0x8f, 0x9e, 0x9f, 0x83, 0x9b, 0xf2, 0x43, 0x59, 0x0d, 0xed,
	0x46, 0x55, 0x62, 0x44, 0x77, 0x78, 0x1a, 0x3a, 0xb4, 0x1a, 0x13, 0x06, 0xaf, 0xc1, 0x8f, 0x95,
	0xc8, 0xcb, 0x4d, 0x98, 0x88, 0xe4, 0xa7, 0xa1, 0x1d, 0x93, 0xe2, 0x80, 0x76, 0x94, 0x2a, 0xd1,
	0xce, 0x1e, 0x29, 0x87, 0x49, 0x4e, 0x93, 0xa9, 0x44, 0x6c, 0x50, 0xdd, 0xf4, 0xb6, 0x35, 0x36,
	0x86, 0x07, 0x89, 0xc5, 0x9a, 0xec, 0xaf, 0x31, 0x54, 0x09, 0x5e, 0x81, 0xaf, 0xe7, 0x8e, 0x50,
	0xee, 0x79, 0x29, 0xb1, 0xb9, 0xc2, 0xd9, 0x6f, 0x07, 0xaa, 0xcb, 0xb2, 0x39, 0x3c, 0x35, 0x9b,
	0x26, 0xb6, 0x8c, 0x51, 0x1c, 0x91, 0x31, 0xab, 0x58, 0x6b, 0x7e, 0x34, 0xa8, 0xbb, 0xd8, 0xd3,
	0x04, 0x8f, 0xd8, 0x04, 0xbc, 0x50, 0x63, 0x2a, 0xde, 0x5f, 0x9d, 0x8c, 0x7a, 0x36, 0xb3, 0x47,
	0xd0, 0xe0, 0xf7, 0xe0, 0x2f, 0xb9, 0xca, 0xd7, 0xa7, 0x0a, 0xde, 0xaf, 0xc3, 0xcd, 0xf8, 0xf7,
	0x4c, 0x3e, 0xc0, 0xe0, 0x1b, 0xaa, 0x50, 0x60, 0x86, 0x29, 0x4a, 0xc9, 0xc5, 0x2d, 0xbb, 0x67,
	0xf5, 0x8c, 0xbe, 0x3c, 0xcd, 0xfc, 0x04, 0x83, 0xf3, 0x59, 0x89, 0x78, 0x35, 0x60, 0xed, 0xe4,
	0xf7, 0xbc, 0x3f, 0xc2, 0x8b, 0x2f, 0x05, 0x26, 0xa2, 0xe1, 0xde, 0xec, 0xfe, 0xac, 0x5a, 0xdb,
	0xbc, 0x16, 0x98, 0x03, 0x8b, 0x77, 0xf9, 0xfe, 0xd2, 0xc2, 0x7f, 0xb1, 0x7f, 0x74, 0xe8, 0x2f,
	0x7c, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xf7, 0x53, 0x08, 0x92, 0x03, 0x00, 0x00,
}
